const data = {
  products: [
    {
      _id: "1",
      name: "Watch Nero",
      category: "Wrist Watch",
      image: "/images/product-1.jpg",
      price: 150,
      countInStock: 20,
      brand: "ABC",
      rating: 4.5,
      numReviews: 10,
      description: "Powerful watch for the century",
    },
    {
      _id: "2",
      name: "New Silver watch",
      category: "Wrist Watch",
      image: "/images/product-2.jpg",
      price: 140,
      countInStock: 25,
      brand: "CDG",
      rating: 4.5,
      numReviews: 15,
      description: "This is an awesome watch",
    },
    {
      _id: "3",
      name: "Nokia phone",
      category: "Mobile Phone",
      image: "/images/product-3.jpg",
      price: 95,
      countInStock: 15,
      brand: "MMG",
      rating: 4,
      numReviews: 20,
      description: "Grreat phone to have",
    },
    {
      _id: "4",
      name: "Ladies shoe",
      category: "Shoe",
      image: "/images/product-4.jpg",
      brand: "HHE",
      price: 130,
      countInStock: 0,
      rating: 4.5,
      numReviews: 25,
      description: "Ladies favourite",
    },
    {
      _id: "5",
      name: "Canvas",
      category: "Casuals",
      image: "/images/product-5.jpg",
      brand: "WST",
      price: 160,
      countInStock: 30,
      rating: 4.5,
      numReviews: 30,
      description: "Powerful watch for the century",
    },
    {
      _id: "6",
      name: "Jean",
      category: "Trousers",
      image: "/images/product-6.jpg",
      brand: "GDD",
      price: 125,
      countInStock: 50,
      rating: 4.5,
      numReviews: 35,
      description: "Powerful watch for the century",
    },
    {
      _id: "7",
      name: "Jean",
      category: "Trousers",
      image: "/images/product-10.jpg",
      brand: "GDD",
      price: 125,
      countInStock: 50,
      rating: 4.5,
      numReviews: 35,
      description: "Powerful watch for the century",
    },
    {
      _id: "8",
      name: "Jean",
      category: "Trousers",
      image: "/images/product-9.jpg",
      brand: "GDD",
      price: 125,
      countInStock: 50,
      rating: 4.5,
      numReviews: 35,
      description: "Powerful watch for the century",
    },
  ],
};

export default data;
